require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'MoodAfrika' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'


  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'



  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  pod 'RNSoundPlayer', :path => '../node_modules/react-native-sound-player'

  pod 'RNReactNativeGetMusicFiles', :path => '../node_modules/react-native-get-music-files'

  pod 'RNAudioVideoTools', :path => '../node_modules/react-native-audio-video-tools'


  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  pod 'react-native-track-player', :path => '../node_modules/react-native-track-player'

  pod 'RNAudio', :path => '../node_modules/react-native-audio'

  target 'MoodAfrikaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
